openapi: "3.0.0"

info:
  title: "Trail REST API"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /health:
    get:
      summary: "Health check"
      responses:
        200:
          description: "OK"
