openapi: "3.0.0"

info:
  title: "Trail REST API"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /health:
    get:
      summary: default route
      tags:
        - app
      operationId: app.routes.health
      responses:
        200:
          description: Welcome to the Trail REST API

  /counties:
    get:
      summary: Get all counties
      tags:
        - Counties
      operationId: app.services.get_all_counties
      responses:
        200:
          description: A list of counties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/County"
    post:
      summary: Create a new county
      tags:
        - Counties
      operationId: app.services.create_county
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - county_name
              properties:
                county_name:
                  type: string
      responses:
        201:
          description: County created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/County"
  /counties/{county_id}:
    get:
      summary: Get a county by ID
      tags:
        - Counties
      operationId: app.services.get_county_by_id
      parameters:
        - name: county_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: County details
        404:
          description: County not found
    put:
      summary: Update a county
      tags:
        - Counties
      operationId: app.services.update_county
      parameters:
        - name: county_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - county_name
              properties:
                county_name:
                  type: string
      responses:
        200:
          description: County updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/County"
    delete:
      summary: Delete a county
      tags:
        - Counties
      operationId: app.services.delete_county
      parameters:
        - name: county_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: County deleted
        404:
          description: County not found


  /locations:
    get:
      summary: Get all locations
      tags:
        - Locations
      operationId: app.services.get_all_locations
      responses:
        200:
          description: A list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Location"
    post:
      summary: Create a new location
      tags:
        - Locations
      operationId: app.services.create_location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_name
              properties:
                location_name:
                  type: string
      responses:
        201:
          description: Location created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
  /locations/{location_id}:
    get:
      summary: Get a location by ID
      tags:
        - Locations
      operationId: app.services.get_location_by_id
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Location details
        404:
          description: Location not found
    put:
      summary: Update a location
      tags:
        - Locations
      operationId: app.services.update_location
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_name
              properties:
                location_name:
                  type: string
      responses:
        200:
          description: Location updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Location"
    delete:
      summary: Delete a location
      tags:
        - Counties
      operationId: app.services.delete_location
      parameters:
        - name: location_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Location deleted
        404:
          description: Location not found

  /surface_types:
    get:
      summary: Get all surface types
      tags:
        - SurfaceTypes
      operationId: app.services.get_all_surface_types
      responses:
        200:
          description: A list of surface types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SurfaceType"
    post:
      summary: Create a new surface type
      tags:
        - SurfaceTypes
      operationId: app.services.create_surface_type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - surface_type_name
              properties:
                surface_type_name:
                  type: string
      responses:
        201:
          description: Surface type created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SurfaceType"

  /surface_types/{surface_type_id}:
    get:
      summary: Get a surface type by ID
      tags:
        - SurfaceTypes
      operationId: app.services.get_surface_type_by_id
      parameters:
        - name: surface_type_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Surface type details
        404:
          description: Surface type not found
    put:
      summary: Update a surface type
      tags:
        - SurfaceTypes
      operationId: app.services.update_surface_type
      parameters:
        - name: surface_type_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - surface_type_name
              properties:
                surface_type_name:
                  type: string
      responses:
        200:
          description: Surface type updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SurfaceType"
    delete:
      summary: Delete a surface type
      tags:
        - SurfaceTypes
      operationId: app.services.delete_surface_type
      parameters:
        - name: surface_type_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Surface type deleted
        404:
          description: Surface type not found

  /route_types:
    get:
      summary: Get all route types
      tags:
        - RouteTypes
      operationId: app.services.get_all_route_types
      responses:
        200:
          description: A list of route types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RouteType"
    post:
      summary: Create a new route type
      tags:
        - RouteTypes
      operationId: app.services.create_route_type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - route_type_name
              properties:
                route_type_name:
                  type: string
      responses:
        201:
          description: Route type created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteType"

  /route_types/{route_type_id}:
    get:
      summary: Get a route type by ID
      tags:
        - RouteTypes
      operationId: app.services.get_route_type_by_id
      parameters:
        - name: route_type_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Route type details
        404:
          description: Route type not found
    put:
      summary: Update a route type
      tags:
        - RouteTypes
      operationId: app.services.update_route_type
      parameters:
        - name: route_type_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - route_type_name
              properties:
                route_type_name:
                  type: string
      responses:
        200:
          description: Route type updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteType"
    delete:
      summary: Delete a route type
      tags:
        - RouteTypes
      operationId: app.services.delete_route_type
      parameters:
        - name: route_type_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Route type deleted
        404:
          description: Route type not found


components:
  schemas:
    County:
      type: object
      properties:
        county_id:
          type: integer
        county_name:
          type: string
      required:
        - county_name

    Location:
      type: object
      properties:
        location_id:
          type: integer
        location_name:
          type: string
      required:
        - location_name

    SurfaceType:
      type: object
      properties:
        surface_type_id:
          type: integer
        surface_type_name:
          type: string
      required:
        - surface_type_name

    RouteType:
      type: object
      properties:
        route_type_id:
          type: integer
        route_type_name:
          type: string
      required:
        - route_type_name